[build]
  publish = "public/"
  command = "mkdir public && find ./glitters \\( -iname '*.jpg' -o -iname '*.png' -o -iname '*.gif' \\) -exec cp '{}' ./public \\; && cp ./glitters/images.json ./public/images.json"

[[redirects]]
  from = "/"
  to = "https://glitterbot.dekoolecentrale.nl"
  status = 301
  
[[redirects]]
  from = "/*"
  to="/189368ce.gif"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/images.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
