name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: npm install and run tests
      run: |
        npm install
        npm run test
